### ISSUE TITLE
Suggestions don't work for command aliases

### ISSUE THREAD

**Issue by Fefo6644** [Incendo/cloud#112]
### Description:
The suggestions for the main command work properly, but for the aliases it isn't handled at all (server fallbacks to online players' names)

### Environment:
* cloud module: cloud-paper
* cloud version: 1.1.0
* Server version: Paper 1.16.3 b248
* Command manager: `PaperCommandManager<CommandSender>`
* Coordinator function whatever: `SimpleCoordinator`
* Brigadier hooking: no
* Paper async tab completions hooking: yes

### Sample code:
```java
// onEnable
final PaperCommandManager<CommandSender> manager;
manager = new PaperCommandManager<>(this, CommandExecutionCoordinator.SimpleCoordinator.simpleCoordinator(),
                                    Function.identity(), Function.identity())

// Possibly irrelevant?
if (manager.queryCapability(CloudBukkitCapabilities.ASYNCHRONOUS_COMPLETION)) {
  manager.registerAsynchronousCompletions();
}

final Command.Builder<CommandSender> base = manager.commandBuilder("playerheads", "pheads", "ph");
manager.command(base.literal("spawnnpc", Description.empty()));
```

### Resulting suggestions:
![gif](https://media.discordapp.net/attachments/710101199642165249/770683481171951646/cloud-brokey.gif)

**Comment by jmanpenilla** [comment]
Fixed with #114
