### ISSUE TITLE
ClassCastException in bukkit help menu when the root command has an argument and subcommand is present

### ISSUE THREAD

**Issue by LillianArmes** [Incendo/cloud#130]
Using cloud-paper (1.1.0), annotations (1.1.0), kyori adventure (4.0.0-SNAPSHOT), and commodore (1.9) on Paper 1.16.4

Full stacktrace: https://hasteb.in/qujisome.txt

Example plugin: https://github.com/LillianArmes/cloud-issue-1/blob/master/src/main/java/me/lillian/cloud/CloudTest.java
How to re-create:
- Execute `/test help` as a player
- Click on the `/issue <target>` command in the help menu

**Comment by jmanpenilla** [comment]
These two commands from your example:
`issue b`
and
`issue <target>`
are ambiguous.
In 1.2.0, these ambiguous cases will be properly detected and disallowed when verifying the command tree.
Sorry about any confusion.
