### ISSUE TITLE
Ambiguous node error when really, it is not, given the constraints with flags

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#136]
While playing around with the syntax, I've run into this problem several times, and it makes it difficult to define commands.

This involves the annotations library, I don't know whether the same happens with the builder.

I have two commands:
```
    @CommandMethod("savedtrain list modules")
    @CommandDescription("Lists all modules in which saved trains are saved")
    private void commandListModules(final CommandSender sender) {
        sender.sendMessage("List of modules");
    }

    @CommandMethod("savedtrain list")
    @CommandDescription("Lists all trains accessible to the player")
    private void commandListSavedTrains(
              final CommandSender sender,
              final @Flag(value="all", description="Show all trains on this server, not just those owned by the player") boolean showAll,
              final @Flag(value="module", suggestions="savedtrainmodules", description="Selects a module to list the saved trains of") String moduleName
    ) {
        sender.sendMessage("List of trains in " + moduleName + " all=" + showAll);
    }
```

One is the command:
`/savedtrain list modules`

The other is:
```
/savedtrain list
/savedtrain list --module something
/savedtrain list --all
```

Despite not being ambiguous, this fails to initialize.
```
cloud.exceptions.AmbiguousNodeException: Ambiguous Node: flags cannot be added as a child to list (All children: modules, flags)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandTree.checkAmbiguity(CommandTree.java:741)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandTree.checkAmbiguity(CommandTree.java:745)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandTree.checkAmbiguity(CommandTree.java:745)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandTree.verifyAndRegister(CommandTree.java:672)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandTree.insertCommand(CommandTree.java:617)
    at com.bergerkiller.bukkit.tc.dep.cloud.CommandManager.command(CommandManager.java:210)
    at com.bergerkiller.bukkit.tc.dep.cloud.annotations.AnnotationParser.parse(AnnotationParser.java:250)
```

I've tried mitigating it with [flags...] as was hinted at on the wiki to no avail.

**Comment by jmanpenilla** [comment]
It seems like these nodes are actually ambiguous, however there could be an argument made that there should be an exception to allow mixing flags and literals. City has not been receptive to making these types of changes when brought up though.

**Comment by bergerkiller** [comment]
Alright, I do wonder how it can be documented so people are aware of this, since it was really easy for me to run into these situations making me think there's a bug. Or these bug reports will keep showing up from other people.

Probably when writing an API from scratch these issues aren't that problematic, it's that I'm converting an existing set of commands to use cloud that I run into such problems. Its similar for https://github.com/Incendo/cloud/issues/137

**Comment by Sauilitired** [comment]
The reason why it's ambiguous in this case is because the flags are created using an optional greedy string, in order for them to work properly with Brigadier. We might want to figure out a solution to this

**Comment by bergerkiller** [comment]
This can argueably be closed too now that this PR was merged: https://github.com/Incendo/cloud/pull/181

As that also makes the demonstration case works (literal overrides the 'flags' argument in that case)

Having flags override variable arguments is more difficult and I don't think that is worth doing.
