### ISSUE TITLE
Argument parser suggestions function is always called with a terminal command sender context

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#140]
When registering a custom argument parser. the CommandContext.getSender() always returns the console sender, even when a player is typing the commands. **This only happens when using the brigadier manager**

On paper, this is:
<pre>com.destroystokyo.paper.console.TerminalConsoleCommandSender</pre>

This is currently rendering personalized suggestions ('suggestions based on what the player can see') impossible.

edit*

This example reproduces the problem using Cloud v1.2.0 branch:
<details>
  <summary>Code</summary>

```java
    private BukkitCommandManager<CommandSender> manager;
    private AnnotationParser<CommandSender> annotationParser;

    public void enable(Plugin plugin) {
        try {
            this.manager = new PaperCommandManager<>(
                    /* Owning plugin */ plugin,
                    /* Coordinator function */ CommandExecutionCoordinator.simpleCoordinator(),
                    /* Command Sender -> C */ Function.identity(),
                    /* C -> Command Sender */ Function.identity()
            );
        } catch (final Exception e) {
            throw new IllegalStateException("Failed to initialize the command manager", e);
        }

        // Register Brigadier mappings
        if (manager.queryCapability(CloudBukkitCapabilities.BRIGADIER)) {
            manager.registerBrigadier();

            CloudBrigadierManager<?, ?> brig = manager.brigadierManager();
            brig.setNativeNumberSuggestions(false);
        }

        // Just a simple class type to register with an argument parser
        class TestClass {
            public String name;

            public TestClass(String name) {
                this.name = name;
            }

            @Override
            public String toString() {
                return this.name;
            }
        }

        // parser supplier will parse TestClass and provide suggestions
        manager.getParserRegistry().registerParserSupplier(TypeToken.get(TestClass.class), (params) -> {
            return new ArgumentParser<CommandSender, TestClass>() {
                @Override
                public ArgumentParseResult<TestClass> parse(
                        CommandContext<CommandSender> commandContext,
                        Queue<String> inputQueue
                ) {
                    final String input = inputQueue.peek();
                    if (input == null) {
                        return ArgumentParseResult.failure(new NoInputProvidedException(
                                this.getClass(),
                                commandContext
                        ));
                    }

                    return ArgumentParseResult.success(new TestClass(inputQueue.poll()));
                }

                @Override
                public List<String> suggestions(
                        final CommandContext<CommandSender> commandContext,
                        final String input
                ) {
                    for (Player player : Bukkit.getOnlinePlayers()) {
                        player.sendMessage("You are " + commandContext.getSender().getClass().getName());
                    }
                    return Arrays.asList("a", "b", "c");
                }
            };
        });

        // register the actual command which uses the parser (/command <test>)
        manager.command(
                manager.commandBuilder("command", Description.of("Test cloud command using a builder"))
                        .argument(TestClass.class, "test", (a) -> {
                        })
                        .handler(context -> {
                            context.getSender().sendMessage("Input: " + context.get("test"));
                        })
        );
    }
```
</details>

On Spigot:
![ScreenShot_2020-11-21 18-54-18](https://user-images.githubusercontent.com/957601/99883977-f83e1980-2c2a-11eb-8382-8f1bfbb0aad4.png)

On paperspigot:
![ScreenShot_2020-11-21 18-56-15](https://user-images.githubusercontent.com/957601/99884012-3d624b80-2c2b-11eb-8b31-d4b39236efde.png)

When not using brigadier manager it works as expected:
![ScreenShot_2020-11-21 19-04-29](https://user-images.githubusercontent.com/957601/99884170-63d4b680-2c2c-11eb-885b-ecb54ac05ca2.png)

**Comment by jmanpenilla** [comment]
This seems to work as expected for me:
```java
.withSuggestionsProvider((context, input) -> {
    if (context.getSender() instanceof Player) {
        Player player = (Player) context.getSender();
        ...
    }
    ...
})
```

**Comment by Sauilitired** [comment]
https://github.com/Incendo/cloud/blob/a264605cf0d3c6e9a93a83ee4a70a856eb9daa68/cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java#L443

this method uses a dummy provider, which is probably where this would be happening then

**Comment by bergerkiller** [comment]
Yup I am using the brigadier manager, so that would check out

**Comment by jmanpenilla** [comment]
The issue is probably due to this:
https://github.com/Incendo/cloud/blob/e25940b64b2af4b4b116059bda5a06dccd5b5bc5/cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/CloudCommodoreManager.java#L58
https://github.com/Incendo/cloud/blob/e25940b64b2af4b4b116059bda5a06dccd5b5bc5/cloud-minecraft/cloud-paper/src/main/java/cloud/commandframework/paper/PaperBrigadierListener.java#L53
https://github.com/Incendo/cloud/blob/fdeaa7d8cc35dd0bee0ab06e3b67915cdbbb11c6/cloud-minecraft/cloud-velocity/src/main/java/cloud/commandframework/velocity/VelocityPluginRegistrationHandler.java#L51

The weird thing is, I was using the brigaider manager in my tests as well. I printout the result of
`context.getSender().getClass().toGenericString()` in my suggestions provider (`ArgumentParser#suggestions`), and get
`public class org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer`

**Comment by bergerkiller** [comment]
I am using the 1.2.0 development branch, maybe this is a bug that was later introduced? Sorry, forgot to mention this

**Comment by bergerkiller** [comment]
I can confirm this only happens when using the brigadier manager.
