### ISSUE TITLE
Provide stacktraces in hover events (with a click event to copy to clipboard) for unknown command errors.

### ISSUE THREAD

**Issue by zml2008** [Incendo/cloud#150]
I'd like to see something like what Sponge has (SpongePowered/SpongeAPI@04f11fb) to show stacktraces on hover for platforms where we have access to rich text -- it makes it a little nicer to see what's going on when unhandled errors happen. Thoughts?

**Comment by jmanpenilla** [comment]
Added to the default CommandExecutionException handler for minecraft-extras (which uses adventure) in https://github.com/Incendo/cloud/commit/7c1dff17819c3f3fb4f164f529c6700dbc994886

Leaving this issue open in case we want to also do something similar for platforms like bungee and fabric where we have access to a rich text API that isn't adventure.

**Comment by Citymonstret** [comment]
> Leaving this issue open in case we want to also do something similar for platforms like bungee and fabric where we have access to a rich text API that isn't adventure.

Closing this one now as it has been open for a year and a half without further attention. Feel free to re-open or open a new issue for a specific platform if this is still relevant.
