### ISSUE TITLE
Improve support for advanced Kotlin features

### ISSUE THREAD

**Issue by NickAcPT** [Incendo/cloud#162]
Kotlin users are usually satisfied with the JVM interoperability that already exists, but sometimes that gets in the way when using some advanced features like Coroutines.

I'd love to see support for some kotlin specific features such as the following:
 - Suspending functions with the help of coroutines
 - Default values provided on the method signatures (for annotated methods)
 - DSL builder for commands

For the `supending fun`/coroutine support, it would be very appreciated if we could pass an instance of a CoroutineScope into the builder/annotation parser/command executor (don't know which one is more appropriate here) and have a way to use it easily inside the `suspend fun`. Support should also be added for builders by addding Extension overloads that made use of `CoroutineScope.(...) -> ...` code blocks

**Comment by Proximyst** [comment]
This is unlikely to be implemented as an official project *at the moment* (cc @Sauilitired). We would definitely appreciate a PR, however.

**Comment by Sauilitired** [comment]
The DSL builder has been implemented. We're not going to implement support for default values, as that's already a part of the annotation syntax. The coroutine support is unlikely to be added into cloud itself. You can already inject values into parameter if you want to, and you can also customize execution by providing a custom execution coordinator.
