### ISSUE TITLE
Add @SuggestionsProvider and @ArgumentParser annotated methods

### ISSUE THREAD

**Issue by Sauilitired** [Incendo/cloud#166]
```java
@SuggestionsProvider("cow")
public List<String> cowSuggestions(CommandContext<C> context, String input) {
  return Collections.singletonList("cow");
}
```

This would only work for named suggestions, which I feel is a fair limitation. We could also allow for an optional target class, which would bind it to a parsed argument type. However, I am still not sure about that.

```java
@ArgumentParser("cow")
public Cow cowParser(CommandContext<C> context, Queue<String> input) {
  return new Cow();
}
```

The ArgumentParser could return a parse result, but it would then be very hard to extract the generic type. I'd also prefer to just listen for exceptions and wrap them in a parse failure. Though, I am open for suggestions.

These methods would be a lot easier to add support to as they have (mostly) fixed signatures.

**Comment by superbiebel** [comment]
would be very handy +1
