### ISSUE TITLE
Feature request: register custom annotation that can mutate an annotated command being built

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#179]
Sometimes you want to modify a large group of commands the same way, for example, adding a flag or generating certain descriptions. For this task it would be very useful to be able to modify the command built by the annotation parser, right before it is registered.

Pseudocode:
```
parser.registerCommandBuilder(MyAnnotation.class, (annotation, builder) -> {
    return builder.flag(CommandFlag.newBuilder("flag").build());
});

@MyAnnotation
@CommandMethod("command test")
private void commandTest(
   etc...
) {
}
```

**Comment by NickAcPT** [comment]
If possible, there should also be a way to mutate the arguments with custom annotations.

**Comment by Sauilitired** [comment]
> If possible, there should also be a way to mutate the arguments with custom annotations.

What do you mean? Can you give an example? The arguments aren't mutable, and you can already use annotations to modify the parser to customise the argument depending on annotations.

**Comment by NickAcPT** [comment]
> > If possible, there should also be a way to mutate the arguments with custom annotations.
> 
> What do you mean? Can you give an example? The arguments aren't mutable, and you can already use annotations to modify the parser to customise the argument depending on annotations.

I don't particularly have an example of what I suggested. Maybe I'm mixing stuff. Do you happen to have an example of using custom annotations to customize the argument parser?
