### ISSUE TITLE
Permission Predicate

### ISSUE THREAD

**Issue by Ckblck** [Incendo/cloud#185]
Hello!

It would be awesome to have a method to filter commands in a customized way.

For instance, in our server we do not make use of permission nodes, so the `Command.Builder#permission(String)` method is not suitable for us.

I am talking about something like this:

```
manager.commandBuilder("command", Description.of("This command requires ADMIN rank."))
        .senderType(Player.class)
        .permissionPredicate(sender -> /* Example */ RanksManager.getPlayerRank(sender) == Rank.ADMIN)
        .handler(handler -> ...
```

If the predicate returns false, the message sent is the generic one of not having the required permissions.
It basically works the same way as the `Command.Builder#permission(String)` method, and it gives more flexibility to the command builder.

Thanks!

**Comment by zml2008** [comment]
I have a bit of a hack around this at the moment using a custom `CommandPermission` implementation -- see https://github.com/PEXPlugins/PermissionsEx/blob/08a8bad798ec6320feb53c8a982c7a297e059395/platform/bukkit/src/main/java/ca/stellardrift/permissionsex/bukkit/PermissionsExPlugin.java#L153.

I'd like to see that kind of pattern accommodated in changes to the permissions handling -- and perhaps a way to handle custom `CommandPermission` implementations without having to extend every single platform's `CommandManager`.
