### ISSUE TITLE
Greedy parsers cannot have functioning suggestions

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#190]
There's a hard limitation that a parser can only provide suggestions for one argument being typed. This is because as input to suggestions, only a single String can be provided. When there are two or more parts in the command queue, it is unclear what part should be sent to the suggestions provider.

A greedy string parser might want to suggest words with spaces in them, while a string[] parser might want to suggest a word for every element.

Because suggestions aren't even asked right now (because it is not clear what should happen), there is no workable solution.

https://github.com/Incendo/cloud/blob/1.4.0-dev/cloud-core/src/main/java/cloud/commandframework/CommandTree.java#L602

CompoundArgument has some special logic tailored to it, but also assumes the last-typed 'element' is what needs suggestions. For greedy parsers that is not valid.

Changing String to Queue\<String\> for suggestions would make it in parity with parsers, but would also break api compatibility. I know no good solution for this.

**Comment by Pablete1234** [comment]
### Non-breaking solutions

#### Option A (small behavior change for greedy parsers)
Make it so a greedy or flag-yielding-greedy parser, will receive a string that is concatenating the remaining input with spaces. Non-greedy parsers will not be affected, and the greedy parsers that do get affected were already broken or mostly non-functioning, so this could be an ok solution.

#### Option B (no behavior change)
The command context could have a property for the currently-parsing-queue, similar to how getRawInput is a thing, would allow the flexibility of using the remaining text for greedy-parser suggestions without compromising breaking behavior anywhere.


### Partial workarround:
A way to work around this issue from within the `suggestions` method is to use the command context's raw input to re-create the real string.
Example (call with commandContext.getRawInput(), input):
```java
  private List<String> getRemainingInput(LinkedList<String> rawInput, String input) {
    if (!options.has(StandardParameters.GREEDY) && !options.has(StandardParameters.FLAG_YIELDING))
      return Collections.singletonList(input);

    List<String> value = new ArrayList<>();

    Iterator<String> it = rawInput.descendingIterator();
    while (it.hasNext()) {
      String val = it.next();
      value.add(val);
      if (val.equals(input)) break;
    }
    Collections.reverse(value);
    return value;
  }
```
This implementation **will** fail if text is repeated, eg: `/msg Player 1 2 3 4 1 7` will create a list with ["1", "7"], as it searches backwards for the first instance of the "input" (which will be 1, as it's the first param), i'm not sure that there's any "easy" fix to that without modifying cloud (see: the two options above).


Is there a chance either of the two non-breaking solutions fit the project? I'd be willing to make and PR either of those two solutions if they'll get accepted.
