### ISSUE TITLE
New string type: Greedy until flag start

### ISSUE THREAD

**Issue by zml2008** [Incendo/cloud#218]
I did a quick version of this in PEX: https://github.com/PEXPlugins/PermissionsEx/blob/8bc0a87e2c9a8e870745c25f90f93dcf66e1b02d/impl-blocks/minecraft/src/main/java/ca/stellardrift/permissionsex/minecraft/command/argument/OptionValueParser.java#L41

The parser acts similar to a greedy string, but it stops parsing as soon as it hits a possible flag start, allowing greedy strings to be used in combination with flags.

Would this sort of argument be useful to anyone else and be worth upstreaming?

**Comment by bergerkiller** [comment]
It would certainly be useful to me! Do you think you could extend this to the String[] argument parser too?
