### ISSUE TITLE
Handle reloading!

### ISSUE THREAD

**Issue by MagmaGuy** [Incendo/cloud#224]
Reloading seems to be very hit and miss, even with brigadier off.

This is my current setup:
[full pom.xml](https://hatebin.com/ikfqlqhsmm)
![image](https://user-images.githubusercontent.com/13719743/106386212-d059f780-63cb-11eb-9031-431c44849f52.png)

I am using plugman to selectively reload my plugin. I can 100% guarantee it was working correctly up until I started using this framework, as it's been a part of my dev workflow for years.

I've tried to narrow the issue down as much as I could. As far as I can tell, the most likely way to get reloads to start running into issues is to use plugman reload to update a plugin. I am aware that this type of operation is not recommended for production servers, but it's an integral part of my development workflow on my test servers as I test all my code remotely and restarting the server every time I tweak a value is extremely time consuming, and remote hotswap solutions are... challenging.

In terms of what breaks: I've seen the commands error, not initialize values, commands running but now doing anything and commands running but only partially running the code they're meant to run. It also seems to be messing with my file save system somehow because it can also at times prevent files from being changed, probably because it's forcing a file save on reload even in instances where it shouldn't, possibly because it is reading that it should be saving from a previous boot, even though those values get updated with each reload and restart.

**Comment by aurorasmiles** [comment]
https://matthewmiller.dev/blog/problem-with-reload/
The same applies to reloading with PlugMan

**Comment by JarFiles** [comment]
While reloading might be useful for development, it usually causes more issues than it solves

**Comment by MagmaGuy** [comment]
> https://matthewmiller.dev/blog/problem-with-reload/
> The same applies to reloading with PlugMan

Like I said, I am aware that it is not recommended. I still use it for development purposes, because it sure beats taking a couple of minutes every time I want to see if I like an effect better with a fire particle or a dust particle. And it is possible to make plugins explicitly reload compatible, which I do.

> While reloading might be useful for development, it usually causes more issues than it solves

Based on my experience over the last 3 going on 4 years I really beg to differ. It is exceedingly rare that reloading actually causes a major issue, and it is a great tool to use for when you're trying to tweak values and need immediate feedback.

**Comment by MagmaGuy** [comment]
Ok so I've further narrowed the issue down.

Reloading for the sake of reloading seems to at least mostly work. The thing that truly breaks it is when you upload new code with the reload.

![image](https://user-images.githubusercontent.com/13719743/107104223-9bf59980-6818-11eb-8d4f-9fd3ad9ea28b.png)

This is the error I was consistently getting when attempting a reload which introduced new code to the plugin.

I have since attempted to add a bit of reflection (I apologize if I perhaps didn't do it in the best way, I really do very little reflection work as I tend to avoid it)

```java
 Function<CommandTree, CommandExecutionCoordinator> commandExecutionCoordinator = null;
        try {
            Class<?> c = Class.forName("cloud.commandframework.execution.CommandExecutionCoordinator");
            Method method = c.getDeclaredMethod("simpleCoordinator");
            commandExecutionCoordinator = (Function<CommandTree, CommandExecutionCoordinator>) method.invoke(Function.class);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            manager = new PaperCommandManager(
                    /* Owning plugin */ MetadataHandler.PLUGIN,
                    /* Coordinator function */ commandExecutionCoordinator,
                    /* Command Sender -> C */ Function.identity(),
                    /* C -> Command Sender */ Function.identity()
            );
        } catch (final Exception e) {
            new WarningMessage("Failed to initialize the command manager");
            /* Disable the plugin */
            MetadataHandler.PLUGIN.getServer().getPluginManager().disablePlugin(MetadataHandler.PLUGIN);
            return;
        }
```

This partly fixed my issue by moving said issue further downstream. Please do let me know if the snippet above is incorrect in some way.

Now the error is as follows:

![image](https://user-images.githubusercontent.com/13719743/107104555-170b7f80-681a-11eb-9da8-76ef358e1d56.png)

After poking around for a while I ended up sort of finding a way to unregister commands on shutdown, which was a promising lead:

```java
        try {
            final Field bukkitCommandMap = Bukkit.getServer().getClass().getDeclaredField("commandMap");
            bukkitCommandMap.setAccessible(true);
            CommandMap commandMap = (CommandMap) bukkitCommandMap.get(Bukkit.getServer());
            new DeveloperMessage("registered: " + commandMap.getCommand("elitemobs").isRegistered());
            commandMap.getCommand("elitemobs").unregister(commandMap);
            new DeveloperMessage("registered: " + commandMap.getCommand("elitemobs").isRegistered());
            commandMap.getCommand("adventurersguild").unregister(commandMap);
            commandMap.getCommand("shareitem").unregister(commandMap);
            new InfoMessage("Unregistered commands!");
        } catch (Exception e) {
            e.printStackTrace();
        }
```

This... works(*). Problem now is that on startup, things don't seem to get registered again *correctly*.

(*) *not really*

The code for registering the commands works just fine on the first startup, just not on any subsequent reload.

To be very specific, it seems like some residual features still work. I can run my main command (/em), but the data it reports back essentially amounts to the plugin not being correctly initialized. In practical terms, a book writes entries about mobs if they are spawned, and even though they visible spawned and act correctly that data can't seem to be read.

Most commands, however, run without any output.

And then, sometimes the stars align and I get this error instead when running commands:

![image](https://user-images.githubusercontent.com/13719743/107104907-ab2a1680-681b-11eb-9672-d2c8387deefd.png)


To be specific, the reason why I know that commands aren't getting registered correctly on a restart is because `new DeveloperMessage("registered: " + commandMap.getCommand("elitemobs").isRegistered());` posts true then false on the first reload, but false and false on every subsequent reload, meaning that it never gets registered on startup after the first reload's shutdown sequence.

**Comment by MagmaGuy** [comment]
Oh and for the sake of transparency this is what line 316 (the one that errors on the command) looks like 
![image](https://user-images.githubusercontent.com/13719743/107104985-08be6300-681c-11eb-9974-3a06c580da42.png)

**Comment by Proximyst** [comment]
This does not seem like a Cloud issue in the slightest. Class loading in Java is and has always been made to load classes, only to never "unload" them; this is likely the root of your issue.

Is this reproducible with proper hotswapping, such as with [DCEVM](https://dcevm.github.io/) or GraalVM (Truffle has better support/capability to hotswap than OpenJDK does, but still a hit-or-miss)?

**Comment by Citymonstret** [comment]
1.7.0 allows you to delete root commands in Bukkit/Paper. This is as far as our reload support will go.
