### ISSUE TITLE
Help handler doesn't recognize aliases for static arguments

### ISSUE THREAD

**Issue by p5nbTgip0r** [Incendo/cloud#262]
# Background info
Issue existed in Cloud 1.4.0 and 1.5.0-dev. I'm using `cloud-jda` as my backend, and I'm using `CommandHelpHandler.queryHelp` to search for commands.

# The problem
When sending a help query for a sub-command, while using an alias for the root static argument, the sub-command will not be matched/found.

As an example, my root command is initialized as:
```kotlin
@CommandMethod("nightscout|ns|bg|bs [source]")
```
And I am initializing my sub-command like so:
```kotlin
@CommandMethod("nightscout token|t [token]")
```

Executing `ns token` works, but if I use the `help` command and query `ns token` it will not show any results for the command: ![](https://cdn.discordapp.com/attachments/670908023388241931/806421501065953320/unknown.png)

# Cause
The issue appears to be coming from `CommandManager.getCommands()`, which the help handler uses, since the root argument's aliases do not seem to be assigned properly for each command in the `getCommands()` list:
![](https://cdn.discordapp.com/attachments/670908023388241931/806423385868468224/unknown.png)

The command tree seems to have the root argument's aliases all set properly, so the problem doesn't lie within the command tree:
![](https://cdn.discordapp.com/attachments/670908023388241931/806398417017765898/unknown.png)

# What I've tried
I've tried changing the parsing orders so my root command is initialized *after* my sub-command but it doesn't make any difference. I've also tried adding the root argument's aliases to one of my sub-command's initialization annotations:
```kotlin
@CommandMethod("nightscout|ns|bg|bs delete|del|d")
```
However, neither of these allow for using an alias for the root argument still (as seen by the help command still searching for matching commands instead of giving the sub-command's help):
![](https://cdn.discordapp.com/attachments/670908023388241931/806426001382703104/unknown.png)

**Comment by Citymonstret** [comment]
I've attempted to replicate the issue in https://github.com/Incendo/cloud/pull/323/commits/95caa79a73657a884302dfb668c3db7214ed31f6 but I cannot replicate the issue.
