### ISSUE TITLE
Flags and optional arguments hidden behind permissions

### ISSUE THREAD

**Issue by Smeja64** [Incendo/cloud#266]
I'd like to propose a feature that would allow to make flags or optional arguments hidden based on the user's permissions - users without a specific permission wouldn't be able to use them, and what is more important, they wouldn't get the argument or flag suggested by Brigadier

**Comment by Citymonstret** [comment]
The way to go about this at the moment would be to create two separate commands (with the same initial path), and add a permission nodes to the individual commands.

I'm not sure this is something we want, but we can consider it.

**Comment by Citymonstret** [comment]
Flags have associated permission nodes, which covers half of the suggestion. We're not going to add permission nodes to the optional arguments as it increases the command tree complexity with very little gain. The behavior can already be implemented by multiple permission--protected command chains with required arguments.
