### ISSUE TITLE
[2.0.0] Suggestion to change default exception handling policy

### ISSUE THREAD

**Issue by A248** [Incendo/cloud#275]
I don't know if this has been suggested before, but I thought I would mention it to bring it under consideration for 2.0.0, as it would require a behavioral change.

The current default behavior of platform implementations is to swallow and log exceptions. Sometimes System.err is used, sometimes a specific logging framework. Here's one example:
https://github.com/Incendo/cloud/blob/8bdaeb1c8cbd318675a99bcc15eda3c70f51ff66/cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/BukkitCommand.java#L156-L174

For Cloud 2.0.0, would it be possible to re-throw exceptions rather than swallow and log them by default?

Regardless of whether exception handlers can be configured for some of these exceptions, defaults matter.

**Comment by Citymonstret** [comment]
Yup. That was poor planning on my part, but then we kind of got stuck with this. This is definitely something I want to improve for v2, as well as cleaning up exception usage internally in general.

**Comment by Citymonstret** [comment]
Re-visiting this 3 years later, we've vastly improved the exception system. However, we've decided that it still makes sense to provide sensible platform-specific defaults (hence the different logging methods -- we use whatever is available to us, and do not force any additional dependencies such as SLF4J). 

We'll never have a default policy which satisfies everyone. From our experience, it makes the least amount of people unhappy to have the default be something that is (kind of) usable out of the box. If you disagree with the default policy, it is now a lot easier to just override it. You can clear all exception handlers and register something that re-routes to your own system, etc.
