### ISSUE TITLE
[2.0.0] Use reverse-DNS ownership-compliant package namespace

### ISSUE THREAD

**Issue by A248** [Incendo/cloud#287]
Despite using the cloud.cloudframework namespace, the Incendo organization doesn't own the cloudframework.cloud domain. In fact, this domain is available for purchase with DNS registrars. Usually, the domain is (and usually should be) owned by the software team which uses its namespace.

This requirement is enforced by Maven Central, so if cloud ever wants to deploy to Central, it'll need to own its namespace.

For 2.0.0 it would be a good idea to use a different namespace which the Incendo organization has domain ownership of. Alternatively, the cloudframework.cloud domain is somewhat expensive but if you'd like to purchase it, that would solve the problem too.

**Comment by broccolai** [comment]
It's packaged under `commandframework.cloud` which we do own, we're also already on maven central

**Comment by A248** [comment]
My bad, I clearly made a mistake here. Apologies.
