### ISSUE TITLE
question about cloud-jda command sender.

### ISSUE THREAD

**Issue by portlek** [Incendo/cloud#340]
how can be [this](https://github.com/Incendo/cloud/blob/master/cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandSender.java#L52) parameter null? there is no chance to be null. the only way to create this class is [this](https://github.com/Incendo/cloud/blob/master/cloud-discord/cloud-jda/src/main/java/cloud/commandframework/jda/JDACommandSender.java#L67) method and it's always notnull.

**Comment by Citymonstret** [comment]
The class is non-final, so you could theoretically extend it and have the implementation use a nullable event. 

This cannot be changed without breaking API compatibility.
