### ISSUE TITLE
Question for Incendo Cloud

### ISSUE THREAD

**Issue by EncryptSL** [Incendo/cloud#370]
Hi guys, i migrated from ACF and i have questions.

I have problem with suggestions, when i have Int parameter, suggestion not working. 
Is there any hack for this situation or something like special or suggestions working only with String ?
```KOTLIN
    @CommandMethod("edit <column> <message>")
    @CommandPermission("echelon.news.edit")
    fun onEditNews(commandSender: CommandSender, @Argument("column", suggestions = "columnsList") column: Int,
    @Argument("message") message: String) {
    }
```

What i need for sending long messages: 
/broadcast Hello incendo cloud.

I must use Array<String> or message can work with String ?
Because in ACF long message works with String. 

Thanks for your answer.

**Comment by mastermc05** [comment]
if yes, that is a client side problem, the client thinks he knows that the only possible suggestion is the range of numbers, so he doesn't ask the server 
in that case you may chose one of 2
1. use string 
2. modify brigadier mapper when enabling brigadier 
```java
manager.brigadierManager().setNativeNumberSuggestions(false); 
```

**Comment by EncryptSL** [comment]
1. Thanks mate, this solved problem.

2. For another stupid like me there is annotation Greedy for long message.
