### ISSUE TITLE
Remove keyword 'final' from MinecraftHelp class.

### ISSUE THREAD

**Issue by Ckblck** [Incendo/cloud#384]
The `final` keyword in the MinecraftHelp class is rendering impossible the extension of this class and the override of methods.

For instance, symbols of these methods cannot be modified as they have been hardcoded in a final class:

```java
private @NonNull Component line(final int length) {
    return ComponentHelper.repeat(
                text("-", this.colors.primary, TextDecoration.STRIKETHROUGH),
                length
        );
}

private @NonNull Component branch() {
    return text("├─", this.colors.accent);
}

private @NonNull Component lastBranch() {
     return text("└─", this.colors.accent);
}
```

I did not submit a pull request as it may conflict with the current linting guidelines (if applicable).

**Comment by alii** [comment]
For future reference, it's useful to maintainers to include a _why_ in issues like this. Why do we want the MinecraftHelp command to be extended? What's the use case/what does it solve etc

**Comment by Citymonstret** [comment]
This is very unlikely to be done, as it opens up a whole can of worms. MinecraftHelp isn't exactly meant to be extended. It's an opinionated implementation of the help system.

**Comment by jpenilla** [comment]
I agree with City, if you still think this is something that needs further discussion you can open a new issue at https://github.com/Incendo/cloud-minecraft
