### ISSUE TITLE
Commands with only optional arguments fail to pass default functionality

### ISSUE THREAD

**Issue by SamB440** [Incendo/cloud#386]
Creating a command such as /ping [target] fails to function. This exact code was working in 1.18, but now fails in 1.19.

Example code:
```java
public class PingCommand {

    @CommandDescription("Displays your or a target players ping")
    @CommandMethod("ping [target]")
    public void onCommand(@NonNull final Player player,
                          @Argument(value = "target", description = "The target player")
                          @Nullable final Player target) {
        if (target == null) {
            player.sendMessage(ChatColor.LIGHT_PURPLE + "Your ping is " + player.spigot().getPing() + "ms");
        } else {
            player.sendMessage(ChatColor.LIGHT_PURPLE + target.getName() + "'s ping is " + target.spigot().getPing() + "ms");
        }
    }
}
```

Doing `/ping` results in (also typed a random non-existent command to compare):
![image](https://user-images.githubusercontent.com/11319274/184969960-0f238c4c-5e01-4975-954c-bc274bfd0855.png)

Doing `/ping Cotander` results in:
![image](https://user-images.githubusercontent.com/11319274/184970190-baeee91a-9aba-4ff7-9afd-cd0294f684e8.png)

For easy testing, this is also reproduceable using the ServerUtils plugin which uses Cloud (https://www.spigotmc.org/resources/serverutils-spigot-bungee-velocity-manage-plugins-in-game.79599/)

Doing `/plugins` results in:
![image](https://user-images.githubusercontent.com/11319274/184970821-56e8cd0d-25cb-4eeb-ba7d-dc007ec9509f.png)

Whilst doing `/plugins -v` results in:
![image](https://user-images.githubusercontent.com/11319274/184970908-314667ce-6d75-4f15-8a1b-62d99fddfccf.png)

Tested on a fresh Paper 1.19.2 server build 130 with only ServerUtils installed.

**Comment by JustEli** [comment]
this is fixed in cloud version 1.8.0-SNAPSHOT
