### ISSUE TITLE
Suggestion: Module for regular vanilla Java, no discord or minecraft stuff.

### ISSUE THREAD

**Issue by TomJuri** [Incendo/cloud#425]
what would be even better is a jline3 module.

**Comment by TehBrian** [comment]
Isn't that accomplished by the cloud-core module?

**Comment by TomJuri** [comment]
well, in every module theres a finished CommandManager (e.g BungeeCord -> BungeeCommandManager extends CommandManager) class and in the core theres only a CommandManager class, so youd have to make your own. I figured it out though.
