### ISSUE TITLE
Domain is parked

### ISSUE THREAD

**Issue by BrycensRanch** [Incendo/cloud#432]
you should probably remove the link to the commandframework.cloud domain if it isn't owned by Incendo/cloud anymore, it's parked.

**Comment by kxmpxtxnt** [comment]
removing an url is not the biggest task in human life

**Comment by kxmpxtxnt** [comment]
how tf can it not be done since march 4

**Comment by jpenilla** [comment]
link is removed from the github page, leaving this open to track other uses
