### ISSUE TITLE
multiple sender types

### ISSUE THREAD

**Issue by MelonHell** [Incendo/cloud#438]
I now have a PaperCommandManager\<CommandSenderWrapper\> but I want CommandSender and Player to work too. Is it possible to somehow add an additional commandSenderMapper?

UPD. oh, github handled \< and \> incorrectly, which caused part of the text to disappear and the meaning of the message was distorted

**Comment by masmc05** [comment]
a player is CommandSender

**Comment by masmc05** [comment]
maybe you want a command to require only 1 type of sender? like only player and not console?

**Comment by MelonHell** [comment]
I want to be able to do two commands with one CommandManager:
- the first one accepts my CommandSenderWrapper as a sender
- the second one accepts Bukkit CommandSender

I tried making PaperCommandManager<Object> but it doesn't work

**Comment by masmc05** [comment]
just in first one transform your wrapper back to original command sender inside the command and that's all

**Comment by MelonHell** [comment]
> just in first one transform your wrapper back to original command sender inside the command and that's all 

I do that, but I'm writing a library using the cloud and I would like a user who does not need a multi-platform Wrapper to be able to use Bukkit CommandSender

**Comment by masmc05** [comment]
i think that will overcomplicate this library for other users that uses cloud with only 1 user 

try to make the command sender easily transformed back to bukkit on bukkit platform, you can make the core to work with command manager with type `? extends WrappedSender`, and bukkit manager type to be `BukkitSender`, also you can make 3 more interfaces, like `BukkitPlayerSender`, `BukkitConsoleSender` and `BukkitOtherSender`, which implements BukkitSender, and specify that method `getBukkitSender` will return respective bukkit sender, console sender and just command sender, which will also allow use of required sender

**Comment by MelonHell** [comment]
unfortunately this does not solve the problem, I just want to add an additional CommandSender type so that the command can accept both Bukkit CommandSender and CommandSenderWrapper

**Comment by jpenilla** [comment]
I don't think something like this is in the scope of cloud, you could wrap a mapper for `Object` to accomplish this yourself, but it seems like possibly an XY problem
