### ISSUE TITLE
How to create a command for a string set using annotations?

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [Incendo/cloud#442]
I want to create a BroadCast command, for example for EssentialsX: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandbroadcast.java
But I don't seem to see the implementation in the documentation or in the example code.
How do I implement such an operation?
This feature is very important to me and I want to use this feature for a very large number of operations.

**Comment by xLikeWATCHDOG** [comment]
No need, because this has been found and solved by myself
```
    @CommandMethod("test c5 a1 [query]")
    @CommandDescription("test c5 a1 command")
    public void test_c5_a1_qu(final @NonNull CommandSender sender, final @Argument("query") String[] query) {
        sender.sendMessage(Arrays.toString(query));
    }
```

**Comment by masmc05** [comment]
> I want to create a BroadCast command, for example for EssentialsX: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandbroadcast.java But I don't seem to see the implementation in the documentation or in the example code. How do I implement such an operation? This feature is very important to me and I want to use this feature for a very large number of operations.

i think you needed the `@Greedy` annotation

**Comment by masmc05** [comment]
on a string argument

**Comment by xLikeWATCHDOG** [comment]
Can you give me an example?
It seems that there is no description of `@Greedy` on Wiki.

**Comment by masmc05** [comment]
https://github.com/Incendo/cloud/blob/a4cc749b91564af57bb7bba36dd8011b556c2b3a/examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java#L509

**Comment by xLikeWATCHDOG** [comment]
Ok Thanks
