### ISSUE TITLE
ProxiedBy annotation is not repeatable (Unable to add multiple "proxies")

### ISSUE THREAD

**Issue by bridgelol** [Incendo/cloud#448]
Currently trying to add multiple "proxies" to one of my commands, tried the classic "|" separation to register multiple commands and realized that wasn't implemented.

It would be lovely to get an update where the ProxiedBy annotation is repeatable or either supports the "|" separation as the CommandMethod annotation does.

**Comment by Citymonstret** [comment]
The `@Command` annotation is now repeatable which makes this obsolete. It's preferred to repeat this annotation rather than using the proxy mechanism as it gives you a lot more control.
