### ISSUE TITLE
StringRange not taken into account when mapping Brigadier suggestions to cloud

### ISSUE THREAD

**Issue by Machine-Maker** [Incendo/cloud#528]
Just add an argument `MultiplePlayerSelectorArgument` and observe the suggestions don't work past the initial `@e` suggestion. The cause is that brigadier suggestions, after typing in `@e` return `[`. The default suggestion filter removes suggestions that do not start with the current word, in this case `@e`. If brig returned `@e[`, then it would work. 

I *think* the best thing, would be to not filter that by default, instead allowing plugins to add such filtering if they wanted. That would mean that within any custom suggestions in custom arguments, you would have to manually match against the current word to return only matching suggestions. Or maybe it could be defined per argument type.

Initial discussion on discord [found here](https://discord.com/channels/766366162388123678/766381452639731722/1134621468949499924).

**Comment by jpenilla** [comment]
The issue here isn't with filtering but with how brig suggestions are mapped to cloud suggestions. The default filtering is something we want to revisit for v2 though.
