### ISSUE TITLE
Compiled CommadTree class is flagged by VirusTotal

### ISSUE THREAD

**Issue by Mr-EmPee** [Incendo/cloud#553]
Compiled Class:
https://www.virustotal.com/gui/file/bf0780eda585f8f210ce29e1c0608d9707f839eba695f6606611e85101734d3d?nocache=1

Source Class:
https://www.virustotal.com/gui/file/d14323fa5f8f66ca94c3554f30efee21eec98babbf2d55314e239e07fe4e6cb3

**Comment by Citymonstret** [comment]
Okay? I don't really see what you want to us to do.

**Comment by Mr-EmPee** [comment]
It poses a significant issue because users who download a plugin may feel alarmed due to the antivirus alert.

**Comment by zml2008** [comment]
Again, what are we supposed to do? if your antivirus is giving false positives, you're the one who's their customer - go yell at them and hope they care enough to fix their broken software.
