### ISSUE TITLE
SuggestionLike

### ISSUE THREAD

**Issue by Machine-Maker** [Incendo/cloud#565]
I think it'd be useful to have some sort of `SuggestionLike` interface that would be returned from SuggestionProvider#suggestions and ArgumentParser#suggestions so custom types didn't always have to be streamed and converted over to suggestion objects.

**Comment by Citymonstret** [comment]
We've opted not to introduce this into cloud-core as it adds quite a lot of additional complexity while not offering a unique solution to any existing issues.
