### ISSUE TITLE
Move to org.incendo.cloud

### ISSUE THREAD

**Issue by Citymonstret** [Incendo/cloud#588]
**We have not decided whether this is something we want to do. This is a proposal, and feedback is welcome.**

We're not going to get the old domain back. I've been wanting to move everything over to `org.incendo.cloud` for a while now, and this is as good of an opportunity as we'll get. 

Cloud v2 is already very impactful and touched about every part of the codebase. Moving the packages is not going to make a big difference when it comes to migrating to v2.

**Comment by jpenilla** [comment]
Done in #660
