### ISSUE TITLE
Please fix the documentation for minecraft users

### ISSUE THREAD

**Issue by mfnalex** [Incendo/cloud#646]
Hello, I have tried to use cloud for a minecraft plugin, but I am really struggling with the whole ecosystem of outdated documentation.

I will try to explain my experience with cloud, step by step:

1. I found this post: https://www.spigotmc.org/threads/cloud-command-framework.467183/
2. I tried to click on the github link: https://commandframework.cloud/ Website not reachable
3. I tried going to the Wiki mentioned there: Error 404: https://incendo.github.io/cloud/
4. I tried to find the javadocs. Same as No. 2, website not reachable: https://javadoc.commandframework.cloud/
5. I tried to check out the linked example plugin: Another error 404: https://github.com/Incendo/cloud/blob/master/examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java
6. Okay, so now I have just googled "cloud commandframework" and found this repository. It's hard to find anything minecraft/spigot related information.
  - The readme tells me 1.8.4 is the latest version to use
  - But just below that, it tells me that version 2.0.0 had many changes. So is 2.0.0 or 1.8.4 the version to use now?
  - I found the link the the minecraft module: https://github.com/incendo/cloud-minecraft That one tells me to use version 2.0.0-SNAPSHOT. In which repository is that? Maven central? No, they don't allow snapshots.
 
I have then joined the discord server, where I was sent a link to the javadocs - which happen to be for version 1.7.X.

All of this experience has been extremely annoying and I'm probably not the only person who thinks like that. I didn't have the opportunity to try out cloud at all, because there was a ton of setbacks because of missing javadocs for the latest version, even knowing what the latest version is supposed to be (2.0.0-SNAPSHOT as the minecraft modue says, or 1.8.4 as the core readme says, or 1.7.X as the javadocs from the discord server say?).

It would really be nice if someone of the people who know more about this project than me could just pretend to be a new user and then adjust the docs so someone like me would be able to understand it. Thank you very much and have a nice day!

**Comment by masmc05** [comment]
> The readme tells me 1.8.4 is the latest version to use 

That really is the latest release version
> But just below that, it tells me that version 2.0.0 had many changes. So is 2.0.0 or 1.8.4 the version to use now?

2.0.0 is the latest version, but it's under development and still only a snapshot
> In which repository is that? Maven central? No, they don't allow snapshots.

check readme on https://github.com/Incendo/cloud for the link for snapshot repo, since as you see, it has "-SNAPSHOT" at the end, meaning it's not a release version


Cloud 2.0 is under development so many docs are messed up because of it, so just have some patience, or you could wait for the release of 2.0 when the situation would stabilize

**Comment by Citymonstret** [comment]
The docs at https://cloud.incendo.org now link back to the v1 docs, and https://github.com/Incendo/cloud/tree/1.9.0-dev/docs now references the latest release version. The links at Spigot have been updated as well.

There is little Cloud v1 documentation for the Minecraft modules and this is not going to change. There will be documentation for Cloud v2 once the modules are stable. This is not a replacement to the JavaDoc which is always up to date.

**Comment by mfnalex** [comment]
Alrighty, thanks for the clarification!
