### ISSUE TITLE
Annotated default-returning methods

### ISSUE THREAD

**Issue by Citymonstret** [Incendo/cloud#667]
Allow `@DefaultValue` to apply to methods, in which case the method will produce a default value. Flexible signatures can be supported with the new annotated method system.

This would be merged after #598.

```java
@DefaultValue("name")
public @NonNull ArgumentParseResult<YourValue> defaultValue(
  final @NonNull CommandContext<YourSenderType> context
) {
  // logic...
  return theValue;
}
```

then in the method, `@DefaultValue(provider = "name")`

We'd have to make the value of `@DefaultValue` default to `""`, which should be fine. We need a small class for housing the name-provider mappings.

**Comment by Pablete1234** [comment]
Should probably also get the "context" of what parameter this is for, so in something like:
```
@CommandMethod("/stuff [a]")
public void doStuff(@DefaultValue("name") @Default("A") Something a) {...}

@CommandMethod("/stuff2 [b]")
public void doStuff(@DefaultValue("name") @Default("B") Something b) {...}
```

you'd be able to check for the default annotation value and do stuff different based on which is used, or maybe custom annotations too

**Comment by Citymonstret** [comment]
I think a better implementation of this would be to have the method return a `DefaultValue` instance, as this means that you can then choose to map annotations to parsed default values, constants _or_ dynamic values. The method will have access to the parameter that it's creating the instance for, alongside the annotations.
