### ISSUE TITLE
Issue with String Suggestions in CommandComponent.Builder#suggestionProvider

### ISSUE THREAD

**Issue by Syrent** [Incendo/cloud#706]
When trying to show suggestions for text inputs using `SuggestionProvider.suggestingStrings`, the suggestions don't appear as expected. The provided code snippet illustrates this issue, where the suggestions for arguments aren't displayed correctly. However, switching to a different method, `SuggestionProvider#suggestionsFuture`, solves this problem, as shown in the subsequent code snippet.
Code Snippet (1):
```kotlin
            optional("leader", StringParser.stringParser()) {
                suggestionProvider(SuggestionProvider.suggestingStrings(Bukkit.getOnlinePlayers().map { it.name }))
            }
```
Result (1):
![image](https://github.com/Incendo/cloud/assets/56670179/189d3373-1fec-43ce-93d8-1fc13d4c9819)
Code Snippet (2):
```kotlin
            optional("leader", StringParser.stringParser()) {
                suggestionProvider { _, _ ->
                    CompletableFuture.completedFuture(Bukkit.getOnlinePlayers().map { Suggestion.suggestion(it.name) })
                }
            }
```
Result (2):
![image](https://github.com/Incendo/cloud/assets/56670179/35172d37-01e2-41cd-9a7f-4010fd0bf6c9)

**Comment by Syrent** [comment]
After testing this with both required and optional arguments, it appears that the issue only occurs with optional arguments.

**Comment by jpenilla** [comment]
The server will have no players at command registration time.
