### ISSUE TITLE
ArgumentPair should support TypeToken

### ISSUE THREAD

**Issue by Machine-Maker** [Incendo/cloud#711]
Currently, argumentpair only supports Pair<Class, Class> which causes some issues where I have a type with a generic (wildcard) as one of the types. There are probably issues with methods having the same signature if you just added overloads that took pairs of typetokens.

**Comment by jpenilla** [comment]
This could be solved with a TypePair/TypeTriple etc that can be created from classes or type tokens. But also I feel like removing ArgumentPair/ArgumentTriple in favor of specialized AggregateParser builders would be better...
