### ISSUE TITLE
Exception handler is not properly handling ParserExceptions

### ISSUE THREAD

**Issue by NonSwag** [Incendo/cloud#725]
parser specific parse exceptions (in my case player/world parse exception from screenshot) are never handled but argument parse exception is handled instead providing the original exception as reason

![ef62a6ee-d7e2-4e4c-9c8a-9e484e6c2216](https://github.com/Incendo/cloud/assets/54660361/ec930574-a4ae-4c68-8917-27c76cb071e6)
![image](https://github.com/Incendo/cloud/assets/54660361/7feba79b-1ce2-457d-b805-5ee33dd20189)

**Comment by Citymonstret** [comment]
You will need to unwrap the argument parse exception. This is mentioned in the documentation: https://cloud.incendo.org/core/#exception-handling
