### ISSUE TITLE
Paper 1.20.6 Support

### ISSUE THREAD

**Issue by NonSwag** [Incendo/cloud#726]
The latest beta release of both paper and cloud do not work together
![image](https://github.com/Incendo/cloud/assets/54660361/ff544780-e979-4c18-935a-217b51873bde)

**Comment by onebeastchris** [comment]
https://github.com/Incendo/cloud-minecraft/commit/4bfb8797dd59053ab24dcd402e266f3a7b8bedd0
this was resolved in that commit - you'd currently have to depend on cloud-paper 2.0.0-SNAPSHOT to be able to use cloud on 1.29.5/1.20.6

**Comment by NonSwag** [comment]
thanks you are right, totally missed that
