### ISSUE TITLE
commandContext.command() is not available from preprocessor

### ISSUE THREAD

**Issue by gepron1x** [Incendo/cloud#751]
https://paste.gg/p/anonymous/1411fd82f4e44714adc84cc8c25c7794 - my preprocessor and error

`Caused by: java.lang.IllegalStateException: The current command is only available once a command has been parsed. Mainly from execution handlers and post processors.` 

Minecraft Paper 1.20
cloud version: 2.0.0-beta.8

**Comment by jpenilla** [comment]
As the error and java doc say the command instance is only available after it has been parsed.
